require_relative '../src/classes/book/book'
require_relative '../src/classes/book/label'
require_relative '../src/classes/author/author'
require_relative '../src/classes/game/game'
require_relative '../src/classes/genre/genre'
require_relative '../src/classes/item/item'
require_relative '../src/classes/music_album/music_album'
